public enum Segmento {

    ALIMENTOS_E_BEBIDAS, CELULOSE_E_PAPEL, CONSTRUCAO, EQUIPAMENTOS_ELETRICOS, FARMACOS_E_EQUIPAMENTOS_DE_SAUDE, FUMO, INDUSTRIA_AUTOMOTIVA,
    INDUSTRIA_CERAMICA, INDUSTRIA_DIVERSA, INDUSTRIA_EXTRATIVA, INDUSTRIA_GRAFICA, MADEIRA_E_MOVEIS, MAQUINAS_E_EQUIPAMENTOS,
    METALMECANICA_E_METALURGIA, OLEO_GAS_E_ELETRICIDADE, PRODUTOS_QUIMICOS_E_PLASTICOS, SANEAMENTO_BASICO, TIC, TEXTIL_CONFECCAO_COURO_E_CALCADOS;


}
